my_vm_definition: |
  apiVersion: kubevirt.io/v1
  kind: VirtualMachine
  metadata:
    name: "{{ my_vm | default('rhel9-vm-' + random_string) }}"
    namespace: "{{ my_namespace | default('vms') }}"
    labels:
      app: ansible-provisioned
      kubevirt.io/dynamic-credentials-support: 'true'
      vm.kubevirt.io/template: rhel9-server-small
      vm.kubevirt.io/template.namespace: openshift
      vm.kubevirt.io/template.revision: '1'
      vm.kubevirt.io/template.version: v0.27.0
  spec:
    running: true
    dataVolumeTemplates:
      - apiVersion: cdi.kubevirt.io/v1beta1
        kind: DataVolume
        metadata:
          name: "{{ my_vm | default('rhel9-vm-' + random_string) }}"
        spec:
          sourceRef:
            kind: DataSource
            name: rhel9
            namespace: openshift-virtualization-os-images
          storage:
            resources:
              requests:
                storage: 30Gi
    template:
      metadata:
        labels:
          kubevirt.io/domain: "{{ my_vm | default('rhel9-vm-' + random_string) }}"
          kubevirt.io/size: small
      spec:
        accessCredentials:
        - sshPublicKey:
            propagationMethod:
              qemuGuestAgent:
                users:
                - cloud-user
            source:
              secret:
                secretName: "{{ my_ssh_secret | default('rgdacosta-pub-key') }}"
        architecture: amd64
        domain:
          cpu:
            cores: 1
            sockets: 1
            threads: 1
          devices:
            disks:
              - disk:
                  bus: virtio
                name: rootdisk
              - disk:
                  bus: virtio
                name: cloudinitdisk
            interfaces:
              - macAddress: "{{ '52:54:00' | random_mac }}"
                masquerade: {}
                model: virtio
                name: default
            networkInterfaceMultiqueue: true
            rng: {}
          features:
            acpi: {}
            smm:
              enabled: true
          firmware:
            bootloader:
              efi: {}
          machine:
            type: pc-q35-rhel9.2.0
          memory:
            guest: 2Gi
        networks:
          - name: default
            pod: {}
        terminationGracePeriodSeconds: 180
        volumes:
          - dataVolume:
              name: "{{ my_vm | default('rhel9-vm-' + random_string) }}"
            name: rootdisk
          - cloudInitConfigDrive:
              userData: |
                #cloud-config
                user: cloud-user
                password: redhat123
                chpasswd:
                  expire: false
                runcmd:
                  - - setsebool
                    - '-P'
                    - virt_qemu_ga_manage_ssh
                    - 'on'
            name: cloudinitdisk
