my_svc_definition: |
  apiVersion: v1
  kind: Service
  metadata:
    name: "{{ my_vm | default('rhel9-vm-' + random_string) }}"
    namespace: "{{ my_namespace | default('vms') }}"
    labels:
      kubevirt.io/domain: "{{ my_vm | default('rhel9-vm-' + random_string) }}"
  spec:
    allocateLoadBalancerNodePorts: true
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: 22
    selector:
      kubevirt.io/domain: "{{ my_vm | default('rhel9-vm-' + random_string) }}"
    sessionAffinity: None
    type: LoadBalancer
