apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: nfs-snapclass
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
driver: truenas/nfs 
deletionPolicy: Delete
