apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: silver 
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - vers=4.1
  - hard
  - timeo=600
  - retrans=2
parameters:
  archiveOnDelete: "true"
