apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gold
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
mountOptions:
  - vers=4.1
  - hard
  - timeo=600
  - retrans=2
  - noatime
  - rsize=1048576
  - wsize=1048576
parameters:
  archiveOnDelete: "false"
