spec:
  template:
    spec:
      containers:
      - name: db
        image: quay.io/rdacosta/mysql-57-rhel7:latest  # Include the image!
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: world-db
      volumes:
      - name: world-db
        persistentVolumeClaim:
          claimName: world-db

