FROM registry.redhat.io/rhel9/nginx-124

COPY config.js \
     index.html \
     style.css \
     app.js \
     background.jpg \
     /opt/app-root/src/

COPY nginx.conf /etc/nginx/conf.d/default.conf

USER 1001
ENTRYPOINT nginx -g "daemon off;"

