FROM registry.redhat.io/rhel9/nginx-124

COPY index.html style.css app.js background.jpg config.template.js index.html /opt/app-root/src/

USER root
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

USER 1001
ENTRYPOINT ["nginx", "-g", "daemon off;"]
