spec:
  template:
    spec:
      volumes:
      - name: fe-config-vol
        secret:
          secretName: fe-config
          items:
          - key: config.js
            path: config.js

      containers:
      - name: frontend
        volumeMounts:
        - name: fe-config-vol
          subPath: config.js
          mountPath: /opt/app-root/src/config.js
