---
apiVersion: v1
kind: Namespace
metadata:
  name: golden-vms
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: basic-rhel9
    kubevirt.io/dynamic-credentials-support: "true"
  name: basic-rhel9
  namespace: golden-vms
spec:
  dataVolumeTemplates:
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      creationTimestamp: null
      name: basic-rhel9
    spec:
      source:
        http:
          url: http://utility:8080/openshift4/images/rhel9.qcow2
      storage:
        resources:
          requests:
            storage: 10Gi
  runStrategy: Halted
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: rhel9
        vm.kubevirt.io/workload: server
      creationTimestamp: null
      labels:
        kubevirt.io/domain: basic-rhel9
        kubevirt.io/size: small
        network.kubevirt.io/headlessService: headless
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            model: virtio
            name: default
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: 2Gi
        resources: {}
      hostname: basic-rhel9
      subdomain: headless
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
      - dataVolume:
          name: basic-rhel9
        name: rootdisk
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            user: cloud-user
            password: redhatocp
            chpasswd: { expire: False }
            ssh_authorized_keys:
                - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGtUW3ismHyuCW4CDdTVOOOq6aySdtYenXFWWx7HJa4VTepkG00aaLId9ocra10hc+MB0GTJMCyabDv3i8NKdi6GDH/aOLVsp/Ewy8DEzZMBlJDCt4v2i4/wU4liw6KgEFkZs+5hnqU8d4QzldyGJ5onr+AGvFOKG68CS0BBl40Z1twf1HhCyx8k6nzD2ovlkxWRFZKPAFrtPCBVvQDkOfVFZF+lwzaSztgAjbFZ4A9jqQyUYx4kOJ5DtRef36ucdUdVQale0+8lICl7/gb142SPpYfhxe88/BJScLPRjvVNeu1TxRmoHtVazqnAoRxQYAn2MoI6AG+w6QuZf8f7aL LabGradingKey
            yum_repos:
              baseos:
                name: baseos
                gpgcheck: False
                baseurl: http://content.example.com/rhel9.5/x86_64/dvd/BaseOS
              appstream:
                name: appstream
                gpgcheck: False
                baseurl: http://content.example.com/rhel9.5/x86_64/dvd/AppStream
            packages:
              - vim-enhanced
              - curl
              - bash-completion
            runcmd:
            - systemctl disable --now firewalld
            - [ setsebool, -P, virt_qemu_ga_manage_ssh, on ]
        name: cloudinitdisk
