apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: restricted-network
spec:
  kubernetes.io/hostname: worker01
  containers:
  - name: my-container
    image: busybox
    command: ["sleep", "3600"]

