apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ansible-hub-file-storage
  namespace: aap
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ocs-external-storagecluster-cephfs

