apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web2-logs
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ocs-external-storagecluster-ceph-rbd-virtualization
  volumeMode: Block
