apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web2-logs
  namespace: webservers
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeMode: Block
