---
apiVersion: v1
kind: Namespace
metadata:
  name: webservers
---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-pub-key
  namespace: webservers
type: Opaque
data:
  ssh-publickey: c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCQVFER3RVVzNpc21IeXVDVzRDRGRUVk9PT3E2YXlTZHRZZW5YRldXeDdISmE0VlRlcGtHMDBhYUxJZDlvY3JhMTBoYytNQjBHVEpNQ3lhYkR2M2k4TktkaTZHREgvYU9MVnNwL0V3eThERXpaTUJsSkRDdDR2Mmk0L3dVNGxpdzZLZ0VGa1pzKzVobnFVOGQ0UXpsZHlHSjVvbnIrQUd2Rk9LRzY4Q1MwQkJsNDBaMXR3ZjFIaEN5eDhrNm56RDJvdmxreFdSRlpLUEFGcnRQQ0JWdlFEa09mVkZaRitsd3phU3p0Z0FqYkZaNEE5anFReVVZeDRrT0o1RHRSZWYzNnVjZFVkVlFhbGUwKzhsSUNsNy9nYjE0MlNQcFlmaHhlODgvQkpTY0xQUmp2Vk5ldTFUeFJtb0h0VmF6cW5Bb1J4UVlBbjJNb0k2QUcrdzZRdVpmOGY3YUwgTGFiR3JhZGluZ0tleQo=
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: gls-metallb-ipaddresspool
  name: web1
  namespace: webservers
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    kubevirt.io/domain: web1
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: gls-metallb-ipaddresspool
  name: web2
  namespace: webservers
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    kubevirt.io/domain: web2
  type: LoadBalancer
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/balance: roundrobin
  name: webserver
  namespace: webservers
spec:
  host: webserver.apps.ocp4.example.com
  port:
    targetPort: http
  to:
    kind: Service
    name: webserver
    weight: 100
  wildcardPolicy: None
---
apiVersion: v1
kind: Service
metadata:
  name: webserver
  namespace: webservers
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webserver 
  type: ClusterIP
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: web1
    kubevirt.io/dynamic-credentials-support: "true"
  name: web1
  namespace: webservers
spec:
  dataVolumeTemplates:
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      name: web1
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
        storageClassName: ocs-external-storagecluster-ceph-rbd-virtualization
        volumeMode: Block
      source:
        http:
          url: http://utility:8080/openshift4/images/rhel9-helloworld.qcow2
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      name: web1-extra-disk-0
    spec:
      preallocation: true
      source:
        blank: {}
      storage:
        resources:
          requests:
            storage: 1Gi
        storageClassName: ocs-external-storagecluster-ceph-rbd-virtualization
  runStrategy: Always
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: rhel9
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/domain: web1
        kubevirt.io/size: small
        app: webserver
        network.kubevirt.io/headlessService: headless
    spec:
      hostname: web1
      subdomain: headless
      accessCredentials:
      - sshPublicKey:
          propagationMethod:
            qemuGuestAgent:
              users:
              - cloud-user
          source:
            secret:
              secretName: ssh-pub-key
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          - disk:
              bus: virtio
            name: disk0
          interfaces:
          - masquerade: {}
            model: virtio
            name: default
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: pc-q35-rhel9.2.0
        memory:
          guest: 2Gi
      evictionStrategy: LiveMigrate
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
      - dataVolume:
          name: web1
        name: rootdisk
      - dataVolume:
          name: web1-extra-disk-0
        name: disk0
      - cloudInitConfigDrive:
          userData: |-
            #cloud-config
            user: cloud-user
            password: redhatocp 
            chpasswd:
              expire: false
            write_files:
              - path: /var/www/html/index.html
                content: |
                  this is web1
              - path: /var/www/html/healthz
                content: |
                  web1 is healthy
            yum_repos:
              baseos:
                name: baseos
                gpgcheck: False
                baseurl: http://content.example.com/rhel9.5/x86_64/dvd/BaseOS
              appstream:
                name: appstream
                gpgcheck: False
                baseurl: http://content.example.com/rhel9.5/x86_64/dvd/AppStream
            packages:
              - bash-completion
              - vim-enhanced
              - curl
            runcmd:
            - [ setsebool, -P, virt_qemu_ga_manage_ssh, on ]
            - [ dnf, update, -y, openssh-server ]
        name: cloudinitdisk
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: web2
    kubevirt.io/dynamic-credentials-support: "true"
  name: web2
  namespace: webservers
spec:
  dataVolumeTemplates:
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      name: web2
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
        storageClassName: ocs-external-storagecluster-ceph-rbd-virtualization
        volumeMode: Block
      source:
        http:
          url: http://utility:8080/openshift4/images/rhel9-helloworld.qcow2
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      name: web2-extra-disk-0
    spec:
      preallocation: true
      source:
        blank: {}
      storage:
        resources:
          requests:
            storage: 1Gi
        storageClassName: ocs-external-storagecluster-ceph-rbd-virtualization
  runStrategy: Always
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: rhel9
        vm.kubevirt.io/workload: server
      labels:
        network.kubevirt.io/headlessService: headless
        kubevirt.io/domain: web2
        kubevirt.io/size: small
        app: webserver
    spec:
      hostname: web2
      subdomain: headless
      accessCredentials:
      - sshPublicKey:
          propagationMethod:
            qemuGuestAgent:
              users:
              - cloud-user
          source:
            secret:
              secretName: ssh-pub-key
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          - disk:
              bus: virtio
            name: disk0
          interfaces:
          - masquerade: {}
            model: virtio
            name: default
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: pc-q35-rhel9.2.0
        memory:
          guest: 2Gi
      evictionStrategy: LiveMigrate
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
      - dataVolume:
          name: web2
        name: rootdisk
      - dataVolume:
          name: web2-extra-disk-0
        name: disk0
      - cloudInitConfigDrive:
          userData: |-
            #cloud-config
            user: cloud-user
            password: redhatocp 
            chpasswd:
              expire: false
            write_files:
              - path: /var/www/html/index.html
                content: |
                  this is web2
              - path: /var/www/html/healthz
                content: |
                  web2 is healthy
            yum_repos:
              baseos:
                name: baseos
                gpgcheck: False
                baseurl: http://content.example.com/rhel9.5/x86_64/dvd/BaseOS
              appstream:
                name: appstream
                gpgcheck: False
                baseurl: http://content.example.com/rhel9.5/x86_64/dvd/AppStream
            packages:
                - bash-completion
                - vim-enhanced
                - curl
            runcmd:
              - [ setsebool, -P, virt_qemu_ga_manage_ssh, on ]
              - [ dnf, update, -y, openssh-server ]
        name: cloudinitdisk
