apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    defaults.template.kubevirt.io/disk: rootdisk
    description: A demonstration template for RHEL9 including secret, and service deployment. 
    iconClass: icon-rhel
    openshift.io/display-name: OpenShift Virtualization Training Custom Template 
    openshift.io/documentation-url: https://github.com/kubevirt/common-templates
    openshift.io/support-url: https://github.com/kubevirt/common-templates/issues
    openshift.kubevirt.io/pronounceable-suffix-for-name-expression: "true"
    operator-sdk/primary-resource: openshift-cnv/ssp-kubevirt-hyperconverged
    operator-sdk/primary-resource-type: SSP.ssp.kubevirt.io
    tags: hidden,kubevirt,virtualmachine,linux,rhel
    template.kubevirt.io/containerdisks: |
      registry.redhat.io/rhel9/rhel-guest-image
    template.kubevirt.io/editable: |
      /objects[0].spec.template.spec.domain.cpu.sockets
      /objects[0].spec.template.spec.domain.cpu.cores
      /objects[0].spec.template.spec.domain.cpu.threads
      /objects[0].spec.template.spec.domain.memory.guest
      /objects[0].spec.template.spec.domain.devices.disks
      /objects[0].spec.template.spec.volumes
      /objects[0].spec.template.spec.networks
    template.kubevirt.io/version: v1alpha1
    template.openshift.io/bindable: "false"
  labels:
    app.kubernetes.io/component: templating
    app.kubernetes.io/managed-by: ssp-operator
    app.kubernetes.io/name: custom-templates
    app.kubernetes.io/part-of: hyperconverged-cluster
    flavor.template.kubevirt.io/small: "true"
    os.template.kubevirt.io/rhel9: "true"
    template.kubevirt.io/default-os-variant: "true"
    template.kubevirt.io/type: vm
    vm.kubevirt.io/template: rhel9-server-small
    vm.kubevirt.io/template.namespace: openshift
    workload.template.kubevirt.io/server: "true"
  name: rhel9-custom
  namespace: openshift
objects:
- apiVersion: kubevirt.io/v1
  kind: VirtualMachine
  metadata:
    annotations:
      vm.kubevirt.io/validations: |
        [
          {
            "name": "minimal-required-memory",
            "path": "jsonpath::.spec.domain.memory.guest",
            "rule": "integer",
            "message": "This VM requires more memory.",
            "min": 1610612736
          }
        ]
    labels:
      app: ${NAME}
      kubevirt.io/dynamic-credentials-support: "true"
      vm.kubevirt.io/template: rhel9-custom
      vm.kubevirt.io/template.namespace: openshift
      vm.kubevirt.io/template.revision: "1"
    name: ${NAME}
  spec:
    dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: ${NAME}
      spec:
        pvc:
          accessModes:
          - ReadWriteMany
          resources:
            requests:
              storage: ${ROOT_DISK_SIZE}
          storageClassName: ${STORAGE_PROVISIONER} 
          volumeMode: Block
        source:
          http:
            url: ${ROOT_DISK} 
    - metadata:
        name: ${NAME}-extra-disk-0
      spec:
        preallocation: true
        source:
          blank: {}
        storage:
          resources:
            requests:
              storage: ${EXTRA_DISK_SIZE}
          storageClassName: ${STORAGE_PROVISIONER} 
    running: false
    template:
      metadata:
        annotations:
          vm.kubevirt.io/flavor: small
          vm.kubevirt.io/os: rhel9
          vm.kubevirt.io/workload: server
        labels:
          kubevirt.io/domain: ${NAME}
          kubevirt.io/size: small
      spec:
        hostname: ${NAME}
        subdomain: headless
        accessCredentials:
        - sshPublicKey:
            propagationMethod:
              qemuGuestAgent:
                users:
                - cloud-user
            source:
              secret:
                secretName: ${SSH_KEY_SECRET}
        domain:
          cpu:
            cores: 2
            sockets: 1
            threads: 2
          devices:
            disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
            - disk:
                bus: virtio
              name: disk0
              shareable: null
            interfaces:
            - masquerade: {}
              model: virtio
              name: default
            networkInterfaceMultiqueue: true
            rng: {}
          features:
            smm:
              enabled: true
          firmware:
            bootloader:
              efi: {}
          machine:
            type: pc-q35-rhel9.2.0
          memory:
            guest: 2Gi
        evictionStrategy: LiveMigrate
        networks:
        - name: default
          pod: {}
        terminationGracePeriodSeconds: 180
        volumes:
        - dataVolume:
            name: ${NAME}
          name: rootdisk
        - dataVolume:
            name: ${NAME}-extra-disk-0
          name: disk0
        - cloudInitConfigDrive:
            userData: |-
              #cloud-config
              user: cloud-user
              password: ${CLOUD_USER_PASSWORD}
              chpasswd:
                expire: false                          
              yum_repos:
                baseos:
                  name: baseos
                  gpgcheck: False
                  baseurl: http://content.example.com/rhel9.4/x86_64/dvd/BaseOS
                appstream:
                  name: appstream
                  gpgcheck: False
                  baseurl: http://content.example.com/rhel9.4/x86_64/dvd/AppStream
              packages:
                - vim-enhanced
                - curl
                - qemu-guest-agent                  
              runcmd:
                - [ setsebool, -P, virt_qemu_ga_manage_ssh, on ]
          name: cloudinitdisk
- apiVersion: v1
  data:
    key: c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCQVFER3RVVzNpc21IeXVDVzRDRGRUVk9PT3E2YXlTZHRZZW5YRldXeDdISmE0VlRlcGtHMDBhYUxJZDlvY3JhMTBoYytNQjBHVEpNQ3lhYkR2M2k4TktkaTZHREgvYU9MVnNwL0V3eThERXpaTUJsSkRDdDR2Mmk0L3dVNGxpdzZLZ0VGa1pzKzVobnFVOGQ0UXpsZHlHSjVvbnIrQUd2Rk9LRzY4Q1MwQkJsNDBaMXR3ZjFIaEN5eDhrNm56RDJvdmxreFdSRlpLUEFGcnRQQ0JWdlFEa09mVkZaRitsd3phU3p0Z0FqYkZaNEE5anFReVVZeDRrT0o1RHRSZWYzNnVjZFVkVlFhbGUwKzhsSUNsNy9nYjE0MlNQcFlmaHhlODgvQkpTY0xQUmp2Vk5ldTFUeFJtb0h0VmF6cW5Bb1J4UVlBbjJNb0k2QUcrdzZRdVpmOGY3YUwgTGFiR3JhZGluZ0tleQo= 
  kind: Secret
  metadata:
    name: ssh-pub-key
  type: Opaque
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: internal
  spec:
    ingress:
    - from:
      - podSelector: {}
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: openshift-cnv
      - namespaceSelector:
          matchLabels:
            network.openshift.io/policy-group: ingress
      ports:
      - port: 80
        protocol: TCP
    podSelector: {}
    policyTypes:
    - Ingress
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      metallb.universe.tf/address-pool: ${METALLB_POOL}
    name: ${NAME}
  spec:
    ports:
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: 22
    selector:
      kubevirt.io/domain: ${NAME}
    type: LoadBalancer
parameters:
- description: VM name
  from: rhel9-[a-z0-9]{16}
  generate: expression
  name: NAME
- description: Password for the cloud-init user cloud-user
  name: CLOUD_USER_PASSWORD
  value: redhatocp
- description: SSH Key Secret
  name: SSH_KEY_SECRET
  value: ssh-pub-key
- description: MetalLB Pool
  name: METALLB_POOL
  value: gls-metallb-ipaddresspool
- description: Storage Provisioner
  name: STORAGE_PROVISIONER
  value: ocs-external-storagecluster-ceph-rbd-virtualization
- description: Root Disk
  name: ROOT_DISK
  value: http://utility:8080/openshift4/images/rhel9.qcow2
- description: Root Disk Size
  name: ROOT_DISK_SIZE
  value: 10Gi
- description: Extra Disk Size
  name: EXTRA_DISK_SIZE
  value: 5Gi
