apiVersion: v1
kind: Namespace
metadata:
  name: webservers
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: |
      [
        {
          "Key": "lowlatency",
          "Operator": "Equal",
          "Value": "true",
          "Effect": "NoExecute"
        }
      ]
