apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: api
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: api
  name: api
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: quay.io/rdacosta/world_api:latest
    from:
      kind: DockerImage
      name: quay.io/rdacosta/world_api:latest
    generation: 2
    importPolicy:
      importMode: Legacy
    name: latest
    referencePolicy:
      type: Source
