apiVersion: v1
kind: Secret
metadata:
  name: db-creds
  namespace: world 
  labels:
    app: db
stringData:
  MYSQL_USER: ricardo
  MYSQL_PASSWORD: redhat123
  MYSQL_ROOT_PASSWORD: redhat321
  MYSQL_DATABASE: world


