apiVersion: v1
kind: Secret
metadata:
  name: api
  namespace: world 
  labels:
    app: api
stringData:
  WORLD_USER: ricardo
  WORLD_PASSWORD: redhat123
  WORLD_DATABASE: world
  WORLD_HOST: db.world.svc


