apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: api
  name: api
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: api
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: deployment
                operator: In
                values:
                - db
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: WORLD_DATABASE
          value: world
        - name: WORLD_HOST
          value: db
        - name: WORLD_PASSWORD
          value: redhat123
        - name: WORLD_USER
          value: ricardo
        image: quay.io/rdacosta/world_api
        imagePullPolicy: IfNotPresent
        name: api
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
