apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: world-db
  namespace: world
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-storage 
  volumeMode: Filesystem
