my_rhv_plan: |
  apiVersion: forklift.konveyor.io/v1beta1
  kind: Plan
  metadata:
    name: rhv-vms-migrate 
    namespace: "{{ my_namespace | default('openshift-mtv') }}"
  spec:
    archived: false
    description: Ansible generated
    targetNamespace: "{{ my_namespace | default('openshift-mtv') }}"
    vms: "{{ my_vm }}"
    warm: false
    provider:
      source:
        name: "{{ my_provider | default('vmware') }}"
        namespace: "{{ my_namespace | default('openshift-mtv') }}"
      destination:
        name: host
        namespace: "{{ my_namespace | default('openshift-mtv') }}"
    map:
      network:
        name: redhat-virtualization-mqf7d
        namespace: openshift-mtv
      storage:
        name: redhat-virtualization-5lm76
        namespace: openshift-mtv

my_vmware_plan: |
  apiVersion: forklift.konveyor.io/v1beta1
  kind: Plan
  metadata:
    name: vmware-vms-migrate
    namespace: openshift-mtv
  spec:
    map:
      network:
        apiVersion: forklift.konveyor.io/v1beta1
        kind: NetworkMap
        name: vmware-netmap
        namespace: openshift-mtv
      storage:
        apiVersion: forklift.konveyor.io/v1beta1
        kind: StorageMap
        name: vmware-8g72m
        namespace: openshift-mtv
    migrateSharedDisks: true
    provider:
      destination:
        apiVersion: forklift.konveyor.io/v1beta1
        kind: Provider
        name: host
        namespace: openshift-mtv
        uid: e2e704ed-4e6f-4cf4-bf5a-561f2820e207
      source:
        apiVersion: forklift.konveyor.io/v1beta1
        kind: Provider
        name: vmware
        namespace: openshift-mtv
    pvcNameTemplateUseGenerateName: true
    targetNamespace: openshift-mtv
    vms:
    - id: "1"
      name: "{{ my_vms }}"

my_migration: |          
  api_version: forklift.konveyor.io/v1beta1
  kind: Migration
  name: "{{ my_vm }}"
  namespace: "{{ my_namespace | default('openshift-mtv') }}"
    metadata:
      name: "{{ my_plan_name | default(my_vmware_migration) }}"
      namespace: "{{ my_namespace | default('openshift-mtv') }}"
    spec:
      plan:
        name: "{{ my_plan_name | default(my_vmware_plan) }}"
        namespace: "{{ my_namespace | default('openshift-mtv') }}"

my_network_map: |
  apiVersion: forklift.konveyor.io/v1beta1
  kind: NetworkMap
  metadata:
    name: vmware-netmap
    namespace: openshift-mtv
  spec:
    map:
    - destination:
        name: secure-net
        namespace: default
        type: multus
      source:
        id: HaNetwork-secure-net
    - destination:
        type: pod
      source:
        id: HaNetwork-VM Network
    provider:
      destination:
        apiVersion: forklift.konveyor.io/v1beta1
        kind: Provider
        name: host
        namespace: openshift-mtv
      source:
        apiVersion: forklift.konveyor.io/v1beta1
        kind: Provider
        name: vmware
        namespace: openshift-mtv

my_storage_map: |
  apiVersion: forklift.konveyor.io/v1beta1
  kind: StorageMap
  metadata:
    name: vmware-storagemap
    namespace: openshift-mtv
  spec:
    map:
    - destination:
        storageClass: ocs-external-storagecluster-ceph-rbd
      source:
        id: 681080e9-9f16f617-a921-000c29608f6d
    provider:
      destination:
        apiVersion: forklift.konveyor.io/v1beta1
        kind: Provider
        name: host
        namespace: openshift-mtv
      source:
        apiVersion: forklift.konveyor.io/v1beta1
        kind: Provider
        name: vmware
        namespace: openshift-mtv
