apiVersion: v1
kind: Pod
metadata:
  name: untrusting-client 
spec:
  containers:
    - name: no-ca-bundle
      image: registry.ocp4.example.com:8443/redhattraining/hello-world-nginx
      resources: {}
