apiVersion: helm.openshift.io/v1beta1
kind: HelmChartRepository
metadata:
  name: gitlab-repo
spec:
  connectionConfig:
    url: https://gitlab.com/rgdacosta/openshift/-/raw/main/helm-charts
  name: Ricardo da Costa's GitLab Repo
