apiVersion: v1
kind: Pod
metadata:
  name: sshd
  namespace: ssh-demo
  labels:
    app: sshd
spec:
  containers:
    - name: sshd
      image: rastasheep/ubuntu-sshd:18.04
      ports:
        - containerPort: 22
      securityContext:
        privileged: false

