apiVersion: velero.io/v1
kind: Backup
metadata:
  name: backup-webservers
  namespace: openshift-adp
  labels:
    velero.io/storage-location: oadp-dpa-1
spec:
  includedNamespaces:
    - webservers
  storageLocation: oadp-dpa-1
  snapshotVolumes: true
