---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: schedule-backup-webservers
  namespace: openshift-adp
spec:
  schedule: '0 2 * * *'
  template:
    includedNamespaces:
      - backup-webservers
    storageLocation: oadp-dpa-1
    snapshotVolumes: true
