apiVersion: batch/v1
kind: CronJob
metadata:
  name: group-sync
  namespace: idm-integration
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: sync
            image: registry.redhat.io/openshift4/ose-cli:latest 
            command:
            - /bin/sh
            - -c
            - oc adm groups sync --sync-config=/etc/config/cron-ldap-sync.yml --confirm
            volumeMounts:
              - mountPath: "/etc/config"
                name: "ldap-sync-volume"
              - mountPath: "/etc/secrets"
                name: "ldap-bind-password"
          volumes:
            - name: "ldap-sync-volume"
              configMap:
                name: idm-cm
            - name: "ldap-bind-password"
              secret:
                secretName: idm-secret
          serviceAccountName: idm-integrator
          serviceAccount: idm-integrator
