apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: runtime-demo
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    securityContext:
      allowPrivilegeEscalation: true
  restartPolicy: Never

