apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: "{{ my_vm }}"
    kubevirt.io/dynamic-credentials-support: "true"
  name: "{{ my_vm }}"
  namespace: "{{ my_namespace | default('vms') }}"
spec:
  dataVolumeTemplates:
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      creationTimestamp: null
      name: "{{ my_vm }}"
    spec:
      source:
        http:
          url: "{{ my_image | default('http://utility:8080/openshift4/images/rhel9.qcow2') }}"
      storage:
        resources:
          requests:
            storage: "{{ my_disk_size | default('10Gi') }}"
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: rhel9
        vm.kubevirt.io/workload: server
      creationTimestamp: null
      labels:
        kubevirt.io/domain: "{{ my_vm }}"
        kubevirt.io/size: small
        network.kubevirt.io/headlessService: headless
    spec:
      accessCredentials:
      - sshPublicKey:
          propagationMethod:
            qemuGuestAgent:
              users:
              - cloud-user
          source:
            secret:
              secretName: "{{ my_ssh_secret | default('ssh-pub-key') }}"
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: {{ my_cpu_count | default('1') }}
          threads: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            model: virtio
            name: default
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: {{ my_memory_size | default('2Gi') }}
        resources: {}
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
      - dataVolume:
          name: "{{ my_vm }}"
        name: rootdisk
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            user: {{ my_user | default('cloud-user') }}
            password: {{ my_password | default('redhatocp') }}
            chpasswd: { expire: False }
            yum_repos:
              baseos:
                name: baseos
                gpgcheck: False
                baseurl: http://content.example.com/rhel9.4/x86_64/dvd/BaseOS
              appstream:
                name: appstream
                gpgcheck: False
                baseurl: http://content.example.com/rhel9.4/x86_64/dvd/AppStream
            packages:
              - vim-enhanced
              - curl
              - bash-completion
            runcmd:
            - [ setsebool, -P, virt_qemu_ga_manage_ssh, on ]
        name: cloudinitdisk
