apiVersion: v1
kind: Pod
metadata:
  name: naughty
  namespace: priv-demo
spec:
  containers:
    - name: sh
      image: busybox
      command: ["sleep", "3600"]
      securityContext:
        privileged: true
  restartPolicy: Never

