---
- name: Add repos 
  hosts: localhost
  gather_facts: false
  become: false
  force_handlers: true

  tasks:

  - name: Ensure BaseOS RPMs repo is added
    ansible.builtin.yum_repository:
      name: baseos
      description: Classroom BaseOS RPMs repo
      file: classroom_repos
      baseurl: http://content.example.com/rhel9.4/x86_64/dvd/BaseOS 
      gpgcheck: False

  - name: Ensure AppStream RPMs repo is added 
    ansible.builtin.yum_repository:
      name: appstream
      description: Classroom AppStream RPMs repo
      file: classroom_repos
      baseurl: http://content.example.com/rhel9.4/x86_64/dvd/AppStream 
      enabled: no

