---
- name: Add network to VM 
  hosts: localhost
  gather_facts: false
  become: false
  force_handlers: true

  tasks:

    - name: Ensure VM is stopped
      redhat.openshift_virtualization.kubevirt_vm:
        name: "{{ my_vm }}"
        namespace: "{{ my_namespace }}"
        running: false
        wait: true

    - name: Ensure network is added 
      kubernetes.core.k8s_json_patch:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        name: "{{ my_vm }}"
        namespace: "{{ my_namespace }}"
        patch:
          - op: add
            path: /spec/template/spec/domain/devices/interfaces/-
            value:
              - name: nic1
                bridge: {}
                model: virtio
                macAddress: 02:42:ac:11:00:02
          - op: add
            path: /spec/template/spec/networks/-
            value:
              - name: nic1
                multus:
                  networkName: default/{{ my_nad }}
        wait: true
        wait_condition:
          type: Ready
          status: "True"

    - name: Ensure VM is started
      redhat.openshift_virtualization.kubevirt_vm:
        name: "{{ my_vm }}"
        namespace: "{{ my_namespace }}"
        running: true
        wait: true

