---
- name: Add NetworkAttachmentDefinition to VM
  hosts: localhost
  gather_facts: false
  become: false
  force_handlers: true

  tasks:

    - name: Ensure interfaces array exists
      kubernetes.core.k8s_json_patch:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        name: "{{ my_vm }}"
        namespace: "{{ my_namespace }}"
        patch:
          - op: add
            path: /spec/template/spec/domain/devices/interfaces
            value: []

    - name: Ensure networks array exists
      kubernetes.core.k8s_json_patch:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        name: "{{ my_vm }}"
        namespace: "{{ my_namespace }}"
        patch:
          - op: add
            path: /spec/template/spec/networks
            value: []

    - name: Ensure NetworkAttachmentDefinition is added
      kubernetes.core.k8s_json_patch:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        name: "{{ my_vm }}"
        namespace: "{{ my_namespace }}"
        patch:
          - op: add
            path: /spec/template/spec/domain/devices/interfaces/-
            value:
              name: nic1
              bridge: {}
              model: virtio
          - op: add
            path: /spec/template/spec/networks/-
            value:
              name: nic1
              multus:
                networkName: default/{{ my_nad }}
        wait: true
        wait_condition:
          type:   Ready
          status: "True"

