---
- name: Add disk to VM
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Ensure disk is added
      kubernetes.core.k8s_json_patch:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        name: "{{ my_vm }}"
        namespace: "{{ my_namespace }}"
        patch:
          - op: add
            path: /spec/dataVolumeTemplates/-
            value:
              metadata:
                name: "{{ my_disk }}"
              spec:
                source:
                  blank: {}
                storage:
                  storageClassName: "{{ my_storageclass }}"
                  accessModes: ["ReadWriteMany"]
                  resources:
                    requests:
                      storage: "{{ my_size }}Gi"
          - op: add
            path: /spec/template/spec/domain/devices/disks/-
            value:
              name: "{{ my_disk }}"
              disk:
                bus: scsi
          - op: add
            path: /spec/template/spec/volumes/-
            value:
              name: "{{ my_disk }}"
              dataVolume:
                name: "{{ my_disk }}"
        wait: true
        wait_condition:
          type:   Ready
          status: "True"

