---
- name: Add disk to VM 
  hosts: localhost
  gather_facts: false
  become: false
  force_handlers: true

  tasks:

    - name: Add extra disk (SCSI) 
      redhat.openshift.k8s:
        state: patched
        kind: VirtualMachine
        api_version: kubevirt.io/v1
        name: "{{ my_vm }}"
        namespace: "{{ my_namespace }}"
        apply: true  
        template: templates/add_disk.j2
        wait: true
        wait_condition:
          type: Ready
          status: "True"
