---
- name: Add labels to VM 
  hosts: localhost
  gather_facts: false
  become: false
  force_handlers: true

  tasks:

    - name: Ensure label(s) exist 
      redhat.openshift.k8s:
        template: templates/add_labels.j2


    - name: Restart VM
      when: my_restart == "Yes"
      block:

      - name: Ensure VM is stopped
        redhat.openshift_virtualization.kubevirt_vm:
          name: "{{ my_vm }}"
          namespace: "{{ my_namespace }}"
          running: false
          wait: true

      - name: Ensure VM is started
        redhat.openshift_virtualization.kubevirt_vm:
          name: "{{ my_vm }}"
          namespace: "{{ my_namespace }}"
          running: true
          wait: true
