---
- name: Add disk to VM
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Ensure patch is rendered into a list 
      set_fact:
        my_patch: "{{ lookup('template','templates/add_disk.j2') | from_json }}"

    - name: Ensure patch is applied 
      kubernetes.core.k8s_json_patch:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        name: "{{ my_vm }}"
        namespace: "{{ my_namespace }}"
        patch: {{ my_patch }}
        wait: true
        wait_condition:
          type: Ready
          status: "True"

