---
- name: Ensure that yum repositories are configured for this job
  hosts: "{{ my_namespace }}-{{ my_vm }}" 
  gather_facts: false
  become: true

  vars:
    repo_map:
      "RHEL 9.4 BaseOS": "http://content.example.com/rhel9.4/x86_64/dvd/BaseOS"
      "RHEL 9.4 AppStream": "http://content.example.com/rhel9.4/x86_64/dvd/AppStream"
      "RHEL 9.4 Additional BaseOS": "http://content.example.com/rhel9.4/x86_64/rhel9-additional/rhel-9-for-x86_64-baseos-rpms"
      "RHEL 9.4 Additional AppStream": "http://content.example.com/rhel9.4/x86_64/rhel9-additional/rhel-9-for-x86_64-appstream-rpms"

  tasks:

    - name: Ensure that my_repo is normalised into a list
      ansible.builtin.set_fact:
        repo_list: "{{ my_repo if my_repo is iterable and my_repo is not string else [my_repo] }}"

    - name: Ensure that yum repositories are defined
      loop: "{{ repo_list }}"
      loop_control:
        loop_var: item
        index_var: index
      ansible.builtin.yum_repository:
        name: "Ansible Defined repo for {{ repo_map[item] }}"
        file: "ansible_{{ tower_job_id }}"
        description: "Ansible Defined repo for {{ repo_map[item] }}"
        baseurl: "{{ repo_map[item] }}"
        enabled: "{{ my_state | default('true') }}"
        gpgcheck: false
