---
- name: Add labels to VM 
  hosts: localhost
  gather_facts: false
  become: false
  force_handlers: true

  tasks:

    - name: Ensure label(s) exist 
      redhat.openshift.k8s:
        template: templates/add_labels.j2

    - name: Print message
      ansible.builtin.debug:
        msg: |

          🚨     🚨     🚨     🚨     🚨     🚨     🚨     🚨     🚨     🚨     🚨     🚨

                  Do not forget to restart your VM for these labels to take effect

          🚨     🚨     🚨     🚨     🚨     🚨     🚨     🚨     🚨     🚨     🚨     🚨
