---
- name: Create service 
  hosts: localhost
  gather_facts: false
  become: false
  force_handlers: true

  tasks:

    - name: Ensure VM service exists
      redhat.openshift.k8s:
        template: templates/vm_service.yml
