---
- name: Create VM
  hosts: localhost
  gather_facts: false
  become: false
  force_handlers: true

  tasks:

    - name: Ensure VM exists
      redhat.openshift.k8s:
        template: templates/create_vm.j2

    - name: Ensure fact controller learns
      ansible.builtin.set_fact:
        my_host: "{{ my_namespace }}-{{ my_vm }}"
