---
- name: Create VM
  hosts: localhost
  gather_facts: false
  become: false
  force_handlers: true

  tasks:

    - name: Deploy VM from template
      redhat.openshift.openshift_process:
        name: "{{ my_template | default('rhel9-server-small') }}"
        namespace_target: "{{ my_namespace | default('vms') }}"
        namespace: "{{ my_template_namespace | default('openshift') }}"
        state: "{{ my_state | default('present') }}"
        parameters:
          NAME: "{{ my_vm }}"
          CLOUD_USER_PASSWORD: "{{ my_password }}"
  
    - name: Ensure VM is configured
      redhat.openshift_virtualization.kubevirt_vm:
        name: "{{ my_vm | default('rhel9-server-small') }}"
        namespace: "{{ _namespace | default('vms') }}"
        running: true
        labels:
          app: "{{ my_vm }}"
          kubevirt.io/dynamic-credentials-support: "true"
        spec:
          accessCredentials:
          - sshPublicKey:
              propagationMethod:
                qemuGuestAgent:
                  users:
                  - cloud-user
              source:
                secret:
                  secretName: "{{ my_ssh_secret | default('ssh-pub-key') }}"

        
