---
- name: Create route 
  hosts: localhost
  gather_facts: false
  become: false
  force_handlers: true

  tasks:

    - name: Ensure app route exists
      redhat.openshift.k8s:
        template: templates/route.yml
