---
- name: Create VM
  hosts: localhost
  gather_facts: false
  become: false
  force_handlers: true

  tasks:
    - name: Get SSH public key from secret
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Secret
        name: "{{ my_ssh_secret | default('ssh-pub-key') }}"
        namespace: "{{ my_namespace | default('vms') }}"
      register: ssh_secret_info
      
    - debug:
        var: ssh_secret_info.resources[0].data.ssh-publickey

    - name: Set SSH public key fact
      when: ssh_secret_info.kubernetes_info is defined and ssh_secret_info.kubernetes_info | length > 0
      set_fact:
        my_ssh_public_key: "{{ ssh_secret_info.kubernetes_info[0].data['id_rsa.pub'] | b64decode }}"

    - name: Deploy VM from template
      redhat.openshift.openshift_process:
        name: "{{ my_template | default('rhel9-server-small') }}"
        namespace_target: "{{ my_namespace | default('vms') }}"
        namespace: "{{ my_template_namespace | default('openshift') }}"
        state: "{{ my_state | default('present') }}"
        parameters:
          NAME: "{{ my_vm }}"
          CLOUD_USER_PASSWORD: "{{ my_password }}"
          SSH_PUBLIC_KEY: "{{ my_ssh_public_key }}"

    - name: Ensure VM is configured
      redhat.openshift_virtualization.kubevirt_vm:
        name: "{{ my_vm | default('rhel9-server-small') }}"
        namespace: "{{ my_namespace | default('vms') }}"
        running: true
        labels:
          app: "{{ my_vm }}"
          kubevirt.io/dynamic-credentials-support: "true"
        spec:
          accessCredentials:
          - sshPublicKey:
              propagationMethod:
                qemuGuestAgent:
                  users:
                  - cloud-user
              source:
                secret:
                  secretName: "{{ my_ssh_secret | default('ssh-pub-key') }}"
