---
- name: Create VM
  hosts: localhost
  gather_facts: false
  become: false
  force_handlers: true

  tasks:

    - name: Ensure VM exists
      redhat.openshift.k8s:
        template: templates/create_vm.j2
