---
- name: Create VM
  hosts: localhost
  gather_facts: false
  become: false
  force_handlers: true

  tasks:

    - name: Ensure VM is created 
      redhat.openshift_virtualization.kubevirt_vm:
        name: "{{ my_vm }}"
        namespace: "{{ my_namespace | default('vms') }}"
        running: true
        instancetype:
          name: "{{ my_instancetype | default('u1.small') }}"
        preference:
          name: "{{ my_preference | default('rhel.9') }}"
        labels:
          app: "{{ my_vm }}"
          kubevirt.io/dynamic-credentials-support: "true"
          network.kubevirt.io/headlessService: headless
        spec:
          dataVolumeTemplates:
            - metadata:
                name: "{{ my_vm }}-volume"
              spec:
                sourceRef:
                  kind: DataSource
                  name: "{{ my_preference }}"
                  namespace: openshift-virtualization-os-images
                storage:
                  resources: {}
          domain:
            devices: {}
          subdomain: headless
          volumes:
            - dataVolume:
                name: "{{ my_vm }}-volume"
              name: rootdisk
            - cloudInitNoCloud:
                userData: |
                  #cloud-config
                  chpasswd:
                    expire: false
                  password: "{{ my_password }}"
                  user: cloud-user
              name: cloudinitdisk
