---
- name: Deploy VM
  hosts: localhost
  gather_facts: false
  become: false
  force_handlers: true

  tasks:

    - name: Ensure token is obtained
      register: openshift_auth_results
      redhat.openshift.openshift_auth:
        host: "{{ my_ocp_api }}"
        username: "{{ my_ocp_user }}"
        password: "{{ my_ocp_pass }}"
        state: present

    - name: Display the contents of the dictionary called openshift_auth_results
      ansible.builtin.debug:
        var: openshift_auth_results['openshift_auth']['api_key']
