---
# This play is reliant on previously gathered facts
- name: Manage Software
  hosts: "{{ my_namespace }}-{{ my_vm }}"
  gather_facts: false
  force_handlers: true

  tasks:

    - name: Ensure {{ my_package | default('bash') }} is at state {{ my_state | default('installed') }}
      become: true
      when: ansible_facts['distribution']  == "RedHat" and ansible_facts['distribution_major_version'] | int >= 8
      ansible.builtin.dnf:
        name: "{{ my_package | default('bash') }}"
        state: "{{ my_state | default('installed') }}"
