---
- name: Manage snapshot 
  hosts: localhost
  gather_facts: false
  become: false
  force_handlers: true

  tasks:

    - name: Ensure snapshot is created
      tags:
        - create
      redhat.openshift.k8s:
        state: present
        definition:
          apiVersion: snapshot.kubevirt.io/v1alpha1
          kind: VirtualMachineSnapshot
          metadata:
            name: "{{ my_vm }}-snapshot-aap"
            namespace: "{{ my_namespace }}"
          spec:
            source:
              apiGroup: kubevirt.io
              kind: VirtualMachine
              name: "{{ my_vm }}"
        wait: true
        wait_condition:
          type: Ready

    - name: Ensure snapshot is restored
      tags:
        - restore
      block:

      - name: Ensure VM is stopped
        redhat.openshift_virtualization.kubevirt_vm:
          name: "{{ my_vm }}"
          namespace: "{{ my_namespace }}"
          running: false
          wait: true

      - name: Ensure snapshot is restored 
        redhat.openshift.k8s:
          state: present
          definition:
            apiVersion: snapshot.kubevirt.io/v1alpha1
            kind: VirtualMachineRestore
            metadata:
              generateName: "{{ my_vm }}-restore-"
              namespace: "{{ my_namespace }}"
            spec:
              target:
                apiGroup: kubevirt.io
                kind: VirtualMachine
                name: "{{ my_vm }}"
              virtualMachineSnapshotName: "{{ my_vm }}-snapshot-aap"
          wait: true
          wait_timeout: 600
          wait_condition:
            type: Ready

      - name: Ensure old snapshot is removed
        redhat.openshift.k8s:
          state: absent
          definition:
            apiVersion: snapshot.kubevirt.io/v1alpha1
            kind: VirtualMachineSnapshot
            metadata:
              name: "{{ my_vm }}-snapshot-aap"
              namespace: "{{ my_namespace }}"
            spec:
              source:
                apiGroup: kubevirt.io
                kind: VirtualMachine
                name: "{{ my_vm }}"
          wait: true
          wait_condition:
            type: Ready


      - name: Ensure VM is started
        redhat.openshift_virtualization.kubevirt_vm:
          name: "{{ my_vm }}"
          namespace: "{{ my_namespace }}"
          running: true
          wait: true

