---
- name: Remove VM
  hosts: localhost
  gather_facts: false
  become: false
  force_handlers: true

  tasks:

    - name: Ensure VM is removed
      redhat.openshift_virtualization.kubevirt_vm:
        name: "{{ my_vm | mandatory('You must specify the VM to remove using the variable my_vm') }}"
        namespace: "{{ my_namespace | default('vms') }}"
        state: absent
