---
- name: Update compute resources 
  hosts: localhost
  gather_facts: false
  become: false
  force_handlers: true

  tasks:

    - name: Update CPU cores and guest memory
      redhat.openshift_virtualization.kubevirt_vm:
        name: "{{ my_vm }}"
        namespace: "{{ my_namespace }}"
        state: present
        spec:
          domain:
            devices: {}
            cpu:
              cores: !!int "{{ my_cpu_cores }}"
            memory:
              guest: "{{ my_memory }}Gi"
