apiVersion: v1
kind: Pod
metadata:
  name: rogue
  namespace: net-demo
spec:
  containers:
    - name: curl
      image: curlimages/curl
      command: ["sh", "-c", "while true; do sleep 3600; done"]

