FROM registry.access.redhat.com/ubi10/nodejs-22:latest
LABEL "io.k8s.display-name"="my-node-app" \
      "io.openshift.s2i.build.image"="registry.access.redhat.com/ubi10/nodejs-22:latest" \
      "io.openshift.s2i.build.source-location"="."

USER root
# Copying in source code
COPY upload/src /tmp/src
# Change file ownership to the assemble user. Builder image must support chown command.
RUN chown -R 1001:0 /tmp/src
USER 1001
# Assemble script sourced from builder image based on user input or image metadata.
# If this file does not exist in the image, the build will fail.
RUN /usr/libexec/s2i/assemble
# Run script sourced from builder image based on user input or image metadata.
# If this file does not exist in the image, the build will fail.
CMD /usr/libexec/s2i/run
