apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-gatekeeper-resource-requirements
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-gatekeeper-resource-requirements-template
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: templates.gatekeeper.sh/v1beta1
                kind: ConstraintTemplate
                metadata:
                  name: resourcerequirements
                spec:
                  crd:
                    spec:
                      names:
                        kind: ResourceRequirements
                  targets:
                    - target: admission.k8s.gatekeeper.sh
                      rego: |
                        package ocp.resources

                        import data.lib.konstraint
                        import data.lib.openshift

                        violation[{"msg": msg}] {
                          openshift.is_workload_kind
                          container := openshift.containers[_]

                          not container.resources
                          msg := konstraint.format(sprintf("Container '%s' has no resource requests or limits defined", [container.name]))
                        }

                        violation[{"msg": msg}] {
                          openshift.is_workload_kind
                          container := openshift.containers[_]

                          not has_field(container.resources, "limits")
                          msg := konstraint.format(sprintf("Container '%s' has no resource limits defined", [container.name]))
                        }

                        violation[{"msg": msg}] {
                          openshift.is_workload_kind
                          container := openshift.containers[_]

                          not has_field(container.resources, "requests")
                          msg := konstraint.format(sprintf("Container '%s' has no resource requests defined", [container.name]))
                        }

                        has_field(obj, field) {
                          obj[field]
                        }
            - complianceType: musthave
              objectDefinition:
                apiVersion: constraints.gatekeeper.sh/v1beta1
                kind: ResourceRequirements
                metadata:
                  name: resourcerequirements
                spec:
                  match:
                    kinds:
                      - apiGroups:
                          - apps.openshift.io
                          - apps
                        kinds:
                          - DeploymentConfig
                          - DaemonSet
                          - Deployment
                          - StatefulSet
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-gatekeeper-resource-audit
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: constraints.gatekeeper.sh/v1beta1
                kind: ResourceRequirements
                metadata:
                  name: resourcerequirements
                status:
                  totalViolations: 0
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-gatekeeper-resource-admission
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: v1
                kind: Event
                metadata:
                  namespace: openshift-gatekeeper-system
                  annotations:
                    constraint_action: deny
                    constraint_kind: ResourceRequirements
                    constraint_name: resourcerequirements
                    event_type: violation
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-gatekeeper-resource-requirements
placementRef:
  name: placement-policy-gatekeeper-resource-requirements
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
  - name: policy-gatekeeper-resource-requirements
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-gatekeeper-resource-requirements
spec:
  clusterSets:
    - default
